jumpserver/luna

src/app/elements/nav/nav.component.ts

1. chrome fullscreen
2. firefox fullscreen
3. ie fullscreen

support chrome firefox and ie explorer fullscreen

---

src/app/elements/ssh-term/ssh-term.component.ts

feat: add ctrl +c and ctrl + v support

---

package-lock.json

Revert "Bump sshpk from 1.13.1 to 1.16.1"

---

src/app/elements/replay/guacamole/guacamole.component.html
src/app/elements/replay/guacamole/guacamole.component.ts
src/app/elements/replay/json/json.component.html
src/app/elements/replay/json/json.component.ts
src/app/model.ts
src/app/pages/replay/replay.component.css
src/app/pages/replay/replay.component.html
src/app/pages/replay/replay.component.ts
src/assets/i18n/zh.json

[update]更新录像回放页面

---

src/app/elements/connect/connect.component.ts
src/app/elements/content-window/content-window.component.html
src/app/elements/guacamole/guacamole.component.ts
src/app/model.ts
src/app/pages/connect/connect.component.ts
src/app/services/http.ts

Revert "feat: 添加Token链接功能"

---

.github/workflows/jms-generic-action-handler.yml

ci(github): 添加JumpServer仓库通用的action

ci(github): 添加JumpServer仓库通用的action

---

src/app/pages/main/main.component.ts

目前只有3个分类, rdp.ssh.mysql, 目前看只需要判断Rdp即可
Closes https://github.com/jumpserver/luna/issues/210

fix(Splitter): 修复拖动按钮没有正常显示的问题

---

src/app/elements/asset-tree/asset-tree.component.ts

Closes https://github.com/jumpserver/trello/issues/66

fix: 修复Luna资产树搜索异常

---

src/app/services/setting.ts

Closes https://github.com/jumpserver/jumpserver/issues/4278

feat: Luna支持从Core中获取favicon

---

src/app/elements/setting/setting.component.html
src/app/elements/setting/setting.component.ts
src/app/model.ts
src/app/services/http.ts
src/assets/i18n/en.json
src/assets/i18n/zh.json

fix: 修正单词拼写

---

src/app/elements/asset-tree/asset-tree.component.ts

Closes https://github.com/jumpserver/jumpserver/issues/5662

fix: 修复快速打开多个终端导致页面崩溃的问题

---

src/app/elements/connect/connect.component.ts
src/app/elements/content-window/content-window.component.html
src/app/elements/guacamole/guacamole.component.html
src/app/elements/guacamole/guacamole.component.ts

* feat: add lion
* feat: add lion
* feat: add lion
* feat: add lion
* feat: add lion
* feat: add lion
* remove manual user dialog
* fix: remote app support
Co-authored-by: Orange <orangemtony@gmail.com>
Co-authored-by: Eric <xplzv@126.com>

v2.10.0 rc1

---

src/app/elements/nav/nav.component.ts

feat: 支持管理员配置导航栏上帮助中的url, 开源版本有跳转到企业版的链接

feat: 支持管理员配置导航栏上帮助中的url, 开源版本有跳转到企业版的链接

---

src/app/globals.ts

feat: 支持 MongoDB 数据库的纳管

---

src/index.html

perf: 解决esc快捷键冲突，长摁esc键可退出全屏模式

perf: 解决esc快捷键冲突，长摁esc键可退出全屏模式

---

src/app/elements/organization/organization.component.ts
src/app/services/http.ts
src/app/services/organization.ts

Revert "fix: luna设置单独的cookie：X-JMS-LUNA-ORG, 和lina区分开"

---

src/app/pages/app.component.ts

Revert "fix: 优化切换tab事件监听方法"

---

src/app/pages/app.component.ts
src/app/services/view.ts

Revert "feat: 增加shift+左/右键盘事件切换tabs"

---

src/app/globals.ts

feat: 支持纳管 clickhouse[Web Terminal]

feat: 支持纳管 clickhouse[Web Terminal]

---

src/app/elements/asset-tree/asset-tree.component.ts
src/app/utils/common.ts

feat: 新建会话时，小窗口打开

---

src/app/elements/connect/connect-dialog/connect-dialog.component.ts
src/app/elements/connect/connect-dialog/connect-method/connect-method.component.ts
src/app/elements/connect/connect.component.ts
src/app/model.ts

perf: 关闭SFTP后，luna界面不显示相应选项

---

src/app/elements/connect/connect-dialog/connect-method/connect-method.component.ts

Revert "perf: 新增 xrdp 协议 rdp7 可下载 rdp 文件"

---

src/app/elements/asset-tree/asset-tree.component.scss
src/app/elements/connect/connect-dialog/connect-method/connect-method.component.ts

Revert "perf:远程应用不输入密码也能下载RDP文件"

---

src/app/services/http.ts

fix: 解决某个组织管理员用户无权在线监控及查看录像问题

---

package-lock.json
package.json
yarn.lock

Revert "build(deps): bump the npm_and_yarn group with 2 updates"

---

src/app/elements/left-bar/left-bar.component.html
src/app/elements/organization/organization.component.ts

Revert "perf: Remove k8s"
